In [1]:
import numpy as np

In [2]:
numpy_array = np.array([1,2,5,9])

In [3]:
print(numpy_array)

[1 2 5 9]


In [4]:
a = np.zeros((2,4))

In [5]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
a.shape

(2, 4)

In [7]:
a.ndim

2

In [8]:
a.size

8

In [9]:
# array de tres dimensiones
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
#array de unos
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
# array con valor definido en la función
np.full((2,3,4),8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [12]:
# array empty, no es predecible
np.empty((2,3,9))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [13]:
#inicializar array con listas de python
my_list = [1,2,3,4,5]
array = np.array(my_list)
print(array)

[1 2 3 4 5]


In [14]:
#crear un array  utilizando una función basada en rangos
#(mínimo, maximo, número de elementos)
print(np.linspace(0, 6, 10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [15]:
#inicializar array con valores aleatorios
np.random.rand(2,3,4)

array([[[0.67413811, 0.1862741 , 0.56614456, 0.03066673],
        [0.78669891, 0.33772151, 0.09668223, 0.94768269],
        [0.87961838, 0.92077104, 0.66430943, 0.94699854]],

       [[0.14503699, 0.22539512, 0.80016697, 0.40796691],
        [0.87724978, 0.58816987, 0.46477007, 0.58601116],
        [0.00823606, 0.98150926, 0.60194041, 0.40809047]]])

In [16]:
#inicializar array con valores aleatorios conforme a una distribución normal
np.random.randn(2,3,4)

array([[[ 0.94210384, -0.17110956,  0.77040095, -0.25392123],
        [ 1.16505403, -1.92727248, -0.46591599, -0.26726489],
        [-0.39455863,  0.59461506,  0.86275712,  0.57200185]],

       [[ 0.34762157, -0.42800264, -1.88467737,  0.39830476],
        [ 0.07075139,  1.50957433, -0.71076036, -0.94665718],
        [-0.02867207,  0.14927078, -0.32260818, -0.22236298]]])

In [17]:
#creación de un array unidimensional 
array_uni = np.array([1,3,5,7,9,11])
print(array_uni.shape)
print(array_uni)

(6,)
[ 1  3  5  7  9 11]


In [18]:
#acceder a los elementos de un array unidimensional
array_uni[4]

np.int64(9)

In [19]:
#acceder a elementos de un array unidimensional usando slicing
array_uni[2:4]

array([5, 7])

In [20]:
#acceder a elementos de un array unidimensional usando Stride
array_uni[0::3]

array([1, 7])

In [21]:
#crear array multidimencional
array_mul = np.array([[1,2,3,4],[5,6,7,8]])
print(array_mul.shape)
array_mul

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
#acceder a los elementos de un array multidimencional
array_mul[0, 3]

np.int64(4)

In [23]:
#acceder a la fila entera de un array multidimencional
array_mul[1, :]

array([5, 6, 7, 8])

In [24]:
#acceder al tercer elemento de las dos primeras filas de un array multidimencional
array_mul[0:2, 2] #obtener de la fila 0 y 1 los elementos en la posición 2
array_mul[:, 2] ##obtener de todas las filas los elementos en la posición 2 

array([3, 7])

In [25]:
#crear un array unidimencional con inicializado con el rango de elementos 0 - 2
array1 = np.arange(28)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [26]:
#cambiar las dimensiones del array y sus longuitudes
array1.shape = (7,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [27]:
#el ejemplo anterior devuelve un nuevo array que apunta a los mismos datos 
#Importante: las modificaciones de un array modificaran el otro
array2 = array1.reshape(4,7)
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [28]:
#modificar valores del segundo array
array2[0,3] = 50
array2

array([[ 0,  1,  2, 50,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [29]:
print('array1', array1)
print('array2', array2)

array1 [[ 0  1  2 50]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
array2 [[ 0  1  2 50  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [30]:
#desemvolver un array multidimencional y devolver un array de una dimensión 
array1.ravel()

array([ 0,  1,  2, 50,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

Operaciones aritméticas

In [31]:
#crear dos arrays unidimencionales
ar1 = np.arange(2,18,2)
ar2 = np.arange(8)
print('array1: ', ar1)
print('array2: ', ar2)

array1:  [ 2  4  6  8 10 12 14 16]
array2:  [0 1 2 3 4 5 6 7]


In [32]:
#suma
ar1 + ar2

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [33]:
#resta
ar1 - ar2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#multiplicación
ar1 * ar2

array([  0,   4,  12,  24,  40,  60,  84, 112])

Broadcasting

si se aplican operaciones aritméticas sobre Arrays que no tienen la misma forma (shape) Numpy aplica una propiedad que se denomina broadcasting

In [35]:
arr1 = np.arange(5)
arr2 = np.array([3])
print('Shape array1: ', arr1.shape)
print('array1: ', arr1)
print()
print('Shape array2: ', arr2.shape)
print('array2: ', arr2)

Shape array1:  (5,)
array1:  [0 1 2 3 4]

Shape array2:  (1,)
array2:  [3]


In [36]:
#suma de ambos arrays
arr1 +  arr2

array([3, 4, 5, 6, 7])

In [37]:
#creación de dos arrays, multidimencional y unidimensional
arr_1 = np.arange(6)
arr_1.shape = (2,3)
arr_2 = np.arange(6,18,4)
print('Shape array1: ', arr_1.shape)
print('array1: ', arr_1)
print()
print('Shape array2: ', arr_2.shape)
print('array2: ', arr_2)

Shape array1:  (2, 3)
array1:  [[0 1 2]
 [3 4 5]]

Shape array2:  (3,)
array2:  [ 6 10 14]


In [38]:
#suma de array multidimensional con unidimensional 
arr_1 + arr_2

array([[ 6, 11, 16],
       [ 9, 14, 19]])

Funciones estadísticas sobre arrays

In [39]:
#creación de un array unidimensional 
arr_one = np.arange(1,20,2)
print('array1: ', arr_one)

array1:  [ 1  3  5  7  9 11 13 15 17 19]


In [40]:
#media de los elementos del array
arr_one.mean()

np.float64(10.0)

In [41]:
#sumar todos los elementos del array
arr_one.sum()

np.int64(100)

Funciones universales eficientes proporcionadas por numpy

In [42]:
#cuadrado de los elementos
np.square(arr_one)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [43]:
#raíz cuadrada
np.sqrt(arr_one)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [44]:
#exponencial
np.exp(arr_one)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [45]:
#logaritmo
np.log(arr_one)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])