Es una librería fundamental para la computación cientifica en python

- proporsiona arrays de N dimensiones
- implementa funciones matemáticas sofisticadas
- proporsiona herramientas para integrar C/C++ y Fortran
- proporsiona mecanismos para facilitar la realización de tareas relacionadas con álgebra lineal o números aleatorios

Arrays

- en numpy cada dimensión se denomina axis
- el número de dimensiones se denimina rank
- la lista de dimensiones con sus correspondiente longitud se denomina shape
- el número total de elementos (multuplicar la longitud de las dimensiones) se denomina size

In [51]:
import numpy as np

zeros_array = np.zeros((2,4)) # array de dos dimensiones
print(zeros_array)
print(zeros_array.shape) # shape
print(zeros_array.ndim) # rank
print(zeros_array.size) # size

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 4)
2
8


zeros_array es un array:
- con 2 axis, el primero de longitud 2 y el segundo de longitud 4
- con un rank igual a 2
- con un shape igual a (2,4)
- con un size igual a 8

In [ ]:
ones_array = np.ones((2,4,6)) # array de tres dimensiones
print(ones_array)
print(ones_array.shape) # shape
print(ones_array.ndim) # rank
print(ones_array.size) # size

In [ ]:
# arrays cuyo valor es indicado como segundo parámetro de la función
np.full((2,4,7), 8)

In [ ]:
# numpy empty no es predecible, inicializa el array con los 
# valores que hayan en memeria en ese momento

np.empty((2,4))

In [ ]:
# inicializando arrays con listas de python

numbers_list = [2,4,6,8]
array_list = np.array(numbers_list)
print(array_list)

array_list_two_dimensions = np.array([numbers_list, [10, 12, 14, 16]])
print(array_list_two_dimensions)


In [ ]:
# creación de un array utilizando una función basada en rangos
#(mínimo, máximo, número de elementos)

array_ranges = np.linspace(0, 6, 10)
print(array_ranges)


In [ ]:
# creación de arrays con valosres aleatorios

random_array = np.random.rand(2,3,4)
print(random_array)

In [ ]:
# inicialización de un array con valores aleatiros conforme a una distrubución normal

random_array_normal = np.random.randn(2,4)
print(random_array_normal)

Acceso a los elementos de un array

In [ ]:
# ejemplo con array de una dimensión

array_uni = np.array([1, 3, 5, 7, 9, 11])
print(array_uni.shape)
print(array_uni.ndim)
print(array_uni)

# accediendo al cuarto elemento
print(array_uni[4])

# slicing
print(array_uni[2:4])

# stride
print(array_uni[0::3])

In [ ]:
# ejemplo con array de una multidimensional
array_mult = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array_mult.shape)
print(array_mult)

# accediendo al cuarto elemento
print(array_mult[0,3]) # fila 0, elemento 3

# accediendo a la fila entera
print(array_mult[1:]) 

# accediendo al tercer elemento de todas las filas
print(array_mult[0:2, 2]) 
print(array_mult[:, 2]) # simplificado

Modificar un Array

In [ ]:
# creación de un array inicializandolo con un rango de 0-27

arr_range = np.arange(28)
print(arr_range)

# cambiar las dimensiones

arr_range.shape = (7,4)
print(arr_range)

# la redimensión del array anterior apunta a los mismos datos
# si se modifica esto modificará el array original

arr_range2 = arr_range.reshape(4, 7)
print(arr_range2)

print('----- modificación de array copia -----')
arr_range2[0,2] = 50

print('array copia: \n', arr_range2)
print('array original: \n', arr_range)

# convertir array multidimensional en unidimensional

arr_range_uni = arr_range2.ravel()
print(arr_range_uni)


Operaciones aaritméticas con arrays

In [60]:
# crear 2 arrays unidimencionales

array_uni_op1 = np.arange(2, 18, 2)
array_uni_op2 = np.arange(8)

print('array 1:\n', array_uni_op1)
print('array 2:\n', array_uni_op2)

print('----- suma -----')
print(array_uni_op1 + array_uni_op2)

print('----- resta -----')
print(array_uni_op1 - array_uni_op2)

print('----- multiplicación -----')
print(array_uni_op1 * array_uni_op2)

array 1:
 [ 2  4  6  8 10 12 14 16]
array 2:
 [0 1 2 3 4 5 6 7]
----- suma -----
[ 2  5  8 11 14 17 20 23]
----- resta -----
[2 3 4 5 6 7 8 9]
----- multiplicación -----
[  0   4  12  24  40  60  84 112]


Broadcasting

Si se aplican operaciones aritméticas con arrays que no tienen la misma forma (shape) numpy aplica una propiedad
que se denomina como broadcasting

In [65]:
# operaciones aritméticad en arrays unidimensionales

array_uni_op3 = np.arange(5)
array_uni_op4 = np.array([3])

print('shape array 1: ', array_uni_op3.shape)
print('array 1: ', array_uni_op3)

print()

print('shape array 2: ', array_uni_op4.shape)
print('array : ', array_uni_op4)

print('----- suma -----')
print(array_uni_op3 + array_uni_op4)

print('----- resta -----')
print(array_uni_op3 - array_uni_op4)

print('----- multiplicación -----')
print(array_uni_op3 * array_uni_op4)

shape array 1:  (5,)
array 1:  [0 1 2 3 4]

shape array 2:  (1,)
array :  [3]
----- suma -----
[3 4 5 6 7]
----- resta -----
[-3 -2 -1  0  1]
----- multiplicación -----
[ 0  3  6  9 12]


In [69]:
# operaciones aritméticads con array multidimensional y unidimensional

array_mult_op1 = np.arange(6)
array_mult_op1.shape = (2,3)
print('shape array 1', array_mult_op1.shape)
print('array 1 \n', array_mult_op1)

print()

array_mult_op2 = np.arange(6, 18, 4)
print('shape array 2', array_mult_op2.shape)
print('array 1 \n', array_mult_op2)

print('----- suma -----')
print(array_mult_op1 + array_mult_op2)

print('----- resta -----')
print(array_mult_op1 - array_mult_op2)

print('----- multiplicación -----')
print(array_mult_op1 * array_mult_op2)


shape array 1 (2, 3)
array 1 
 [[0 1 2]
 [3 4 5]]

shape array 2 (3,)
array 1 
 [ 6 10 14]
----- suma -----
[[ 6 11 16]
 [ 9 14 19]]
----- resta -----
[[ -6  -9 -12]
 [ -3  -6  -9]]
----- multiplicación -----
[[ 0 10 28]
 [18 40 70]]


Funciones estadísticas sobre arrays

In [72]:
# crear array unidimensiona

array_est1 = np.arange(1, 20, 2)
print('array 1: \n', array_est1)

# calcular la media de todos los valores de un array

print(array_est1.mean())

# suma de los elementos
print(array_est1.sum())

array 1: 
 [ 1  3  5  7  9 11 13 15 17 19]
10.0
100


Funciones universales eficientes proporsionadas por numpy

In [77]:
# cuadrado de los elementos de un array

array_ufunc = np.arange(1, 20, 2)

print('----- square -----')
print(np.square(array_ufunc))

# raíz cuadrada de los elementos de un array

print('----- sqrt -----')
print(np.sqrt(array_ufunc))

# exponencial de los elementos de un array

print('----- exp -----')
print(np.exp(array_ufunc))

# logaritmo de los elementos de un array

print('----- log -----')
print(np.log(array_ufunc))

----- square -----
[  1   9  25  49  81 121 169 225 289 361]
----- sqrt -----
[1.         1.73205081 2.23606798 2.64575131 3.         3.31662479
 3.60555128 3.87298335 4.12310563 4.35889894]
----- exp -----
[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03 5.98741417e+04 4.42413392e+05 3.26901737e+06
 2.41549528e+07 1.78482301e+08]
----- log -----
[0.         1.09861229 1.60943791 1.94591015 2.19722458 2.39789527
 2.56494936 2.7080502  2.83321334 2.94443898]
